export interface SeedStandard {
  standard_number: string;
  title: string;
  scope: string;
  description: string;
  category: string;
  industry: string;
  technical_committee: string;
  publication_year: number;
  revision_information: string;
  amendments: string;
  related_standards: string[];
  certification_information: string;
  testing_information: string;
  source: string;
  source_url: string;
  keywords: string[];
  is_verified: boolean;
}

export const INITIAL_STANDARDS_DATA: SeedStandard[] = [
  {
    standard_number: "IS 456:2000",
    title: "Plain and Reinforced Concrete - Code of Practice",
    scope: "This standard deals with the general structural use of plain and reinforced concrete. It covers materials, workmanship, inspection and testing, general design requirements, limit state design for flexure, compression, shear and torsion, and detailing requirements for reinforced concrete structures.",
    description: "The primary national standard used in India for the structural design and construction of plain and reinforced concrete buildings, bridges, and infrastructure elements using Limit State Design.",
    category: "Civil Engineering",
    industry: "Construction & Infrastructure",
    technical_committee: "CED 2 (Cement and Concrete Sectional Committee)",
    publication_year: 2000,
    revision_information: "Fourth Revision, Reaffirmed 2021",
    amendments: "Amendments No. 1 to 5 incorporated",
    related_standards: ["IS 875", "IS 10262", "IS 1786", "IS 383", "IS 1343", "IS 13920", "IS 516"],
    certification_information: "Widely referenced in National Building Code of India (NBC) and mandatory compliance for CPWD and State PWD building tenders.",
    testing_information: "Prescribes 28-day characteristic compressive strength cube testing (150mm cubes) tested in accordance with IS 516.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["concrete", "reinforced concrete", "structural design", "limit state", "slump", "beam", "column", "slab", "characteristic strength", "RCC"],
    is_verified: true
  },
  {
    standard_number: "IS 800:2007",
    title: "General Construction in Steel - Code of Practice",
    scope: "This code applies to general construction using hot rolled steel sections joined by bolting, riveting or welding. It adopts the Limit State Design philosophy covering design of tension members, compression members, flexural members, beam-columns, connections, and fabrication and erection.",
    description: "The definitive Indian code for designing steel structures including industrial warehouses, transmission towers, bridges, and multistorey steel frame buildings using Limit State Method.",
    category: "Civil Engineering",
    industry: "Steel & Construction",
    technical_committee: "CED 7 (Structural Engineering and Structural Sections)",
    publication_year: 2007,
    revision_information: "Third Revision, Reaffirmed 2017",
    amendments: "Amendment No. 1 and 2 incorporated",
    related_standards: ["IS 2062", "IS 875", "IS 808", "IS 4000", "IS 816"],
    certification_information: "Statutory code under NBC for all structural steel design and fabrication in India.",
    testing_information: "Mandates raw structural steel conformity to IS 2062, tensile testing per IS 1608, and weld ultrasonic testing per IS 4225.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["steel", "structural steel", "hot rolled sections", "welding", "bolted connections", "limit state", "truss", "gantry girder", "plate girder"],
    is_verified: true
  },
  {
    standard_number: "IS 10262:2019",
    title: "Concrete Mix Proportioning - Guidelines",
    scope: "This standard provides guidelines for proportioning concrete mixes as per the requirements using concrete making materials including other supplementary cementitious materials (SCM) like fly ash, GGBS, silica fume, and chemical admixtures. Covers standard, high-strength, self-compacting, and mass concrete.",
    description: "Authoritative engineering guideline used by concrete batching plants, ready-mix suppliers, and civil engineers to calculate exact cement, water, aggregate, and admixture ratios for targeted strength grades.",
    category: "Civil Engineering",
    industry: "Cement & Concrete",
    technical_committee: "CED 2 (Cement and Concrete Sectional Committee)",
    publication_year: 2019,
    revision_information: "Second Revision (Supercedes IS 10262:2009)",
    amendments: "Latest revision updated with High Strength and Self-Compacting Concrete (SCC)",
    related_standards: ["IS 456", "IS 383", "IS 9103", "IS 3812", "IS 516"],
    certification_information: "Recommended guidelines referenced by National Ready Mixed Concrete Quality Benchmark (RMC-Q).",
    testing_information: "Trial mix testing for workability (slump flow, V-funnel) and compressive strength at 7 and 28 days as per IS 516.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["concrete mix design", "mix proportioning", "water cement ratio", "fly ash", "high strength concrete", "RMC", "slump"],
    is_verified: true
  },
  {
    standard_number: "IS 383:2016",
    title: "Coarse and Fine Aggregate for Concrete - Specification",
    scope: "This standard covers the requirements for aggregates, crushed or uncrushed, derived from natural sources and manufactured/recycled aggregates for use in the production of concrete for normal structural purposes.",
    description: "Mandatory specification for sand, gravel, stone ballast, manufactured sand (M-sand), and recycled concrete aggregate used in all structural concrete across India.",
    category: "Civil Engineering",
    industry: "Construction Aggregates",
    technical_committee: "CED 2 (Cement and Concrete Sectional Committee)",
    publication_year: 2016,
    revision_information: "Third Revision 2016",
    amendments: "Introduced recycled concrete aggregate and manufactured sand (M-sand) grading limits",
    related_standards: ["IS 2386", "IS 456", "IS 10262"],
    certification_information: "Conformity to IS 383 required for government public works, highways (MoRTH), and railways (RDSO).",
    testing_information: "Sieve analysis, flakiness and elongation index, specific gravity, aggregate crushing value, and alkali-silica reactivity per IS 2386.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["aggregate", "coarse aggregate", "fine aggregate", "sand", "m-sand", "crushed stone", "sieve analysis", "grading zone"],
    is_verified: true
  },
  {
    standard_number: "IS 1786:2008",
    title: "High Strength Deformed Steel Bars and Wires for Concrete Reinforcement - Specification",
    scope: "This standard covers the requirements of deformed steel bars and wires for use as reinforcement in concrete in the following strength grades: Fe 415, Fe 415D, Fe 500, Fe 500D, Fe 550, Fe 550D, and Fe 600.",
    description: "The mandatory Indian standard for TMT (Thermo-Mechanically Treated) reinforcement rebar used in all reinforced cement concrete (RCC) construction.",
    category: "Civil Engineering",
    industry: "Steel & Metallurgy",
    technical_committee: "CED 54 (Concrete Reinforcement Sectional Committee)",
    publication_year: 2008,
    revision_information: "Fourth Revision, Reaffirmed 2018",
    amendments: "Amendments 1 to 3 incorporated with strict elongation and ductile ('D') grade requirements for earthquake zones",
    related_standards: ["IS 456", "IS 13920", "IS 1608", "IS 1599"],
    certification_information: "Mandatory ISI Certification (Scheme I). Illegal to manufacture, store, or sell reinforcement steel without BIS Licence under Steel & Steel Products QCO.",
    testing_information: "0.2% Proof stress / yield stress, ultimate tensile strength (TS/YS ratio), percentage elongation, bend and rebend testing per IS 1599 and IS 1608.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["TMT bars", "steel reinforcement", "rebar", "Fe 500D", "Fe 550D", "tensile strength", "ductility", "proof stress"],
    is_verified: true
  },
  {
    standard_number: "IS 2062:2011",
    title: "Hot Rolled Medium and High Tensile Structural Steel - Specification",
    scope: "This standard covers the requirements of hot rolled medium and high tensile structural steel plates, sections, flats, bars, etc., for use in structural work in riveted, bolted, or welded construction.",
    description: "Defines grades of structural steel like E250, E300, E350, E410, and E450 used for steel columns, I-beams, bridge girders, transmission towers, and industrial framing.",
    category: "Civil Engineering",
    industry: "Steel & Metallurgy",
    technical_committee: "MTD 4 (Wrought Steels Sectional Committee)",
    publication_year: 2011,
    revision_information: "Seventh Revision, Reaffirmed 2016",
    amendments: "Amendments 1 and 2 incorporated",
    related_standards: ["IS 800", "IS 1608", "IS 1757", "IS 1599"],
    certification_information: "Mandatory ISI certification under Ministry of Steel Quality Control Order.",
    testing_information: "Tensile test (IS 1608), Charpy impact V-notch test at sub-zero temperatures (IS 1757), and chemical ladle analysis for carbon equivalent (CE).",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["structural steel", "hot rolled steel", "E250", "E350", "steel plates", "charpy impact", "yield stress", "carbon equivalent"],
    is_verified: true
  },
  {
    standard_number: "IS 1343:2012",
    title: "Prestressed Concrete - Code of Practice",
    scope: "This code deals with the general structural use of prestressed concrete. It covers both pretensioned and post-tensioned members, materials, design considerations, losses of prestress, limit states, and detailing.",
    description: "The primary design code in India for prestressed concrete elements such as flyover girders, railway sleepers, metro viaduct segments, and long-span bridge decks.",
    category: "Civil Engineering",
    industry: "Construction & Infrastructure",
    technical_committee: "CED 2 (Cement and Concrete Sectional Committee)",
    publication_year: 2012,
    revision_information: "Second Revision, Reaffirmed 2017",
    amendments: "Updated to limit state principles aligned with contemporary international bridge standards",
    related_standards: ["IS 456", "IS 14268", "IS 2090", "IS 1785"],
    certification_information: "Governs structural safety approvals in NHAI, Indian Railways (RDSO), and Metro Rail Authorities.",
    testing_information: "Specifies testing of high-tensile prestressing strands as per IS 14268, anchorage efficiency tests, and grout testing.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["prestressed concrete", "post-tensioning", "pre-tensioning", "prestressing tendons", "grouting", "anchorage", "viaduct"],
    is_verified: true
  },
  {
    standard_number: "IS 875 (Part 1 to 5):1987",
    title: "Code of Practice for Design Loads (Other Than Earthquake) for Buildings and Structures",
    scope: "Provides unit weights of building materials, stored materials, and design loads: Part 1 (Dead Loads), Part 2 (Imposed/Live Loads), Part 3 (Wind Loads, rev 2015), Part 4 (Snow Loads), and Part 5 (Special Loads and Combinations).",
    description: "The foundational Indian structural standard defining all wind velocities, floor live loads, roof loads, and dead load computations for building design.",
    category: "Civil Engineering",
    industry: "Structural Engineering",
    technical_committee: "CED 57 (Structural Safety Sectional Committee)",
    publication_year: 1987,
    revision_information: "Second Revision, Part 3 thoroughly revised in 2015",
    amendments: "Wind load map updated to 6 basic wind speed zones (33 m/s to 55 m/s)",
    related_standards: ["IS 456", "IS 800", "IS 1893"],
    certification_information: "Mandatory structural calculation standard referenced by Municipal Corporations and NBC.",
    testing_information: "Terrain roughness, k1 risk coefficient, k2 terrain height factor, k3 topography factor, and wind tunnel testing protocols.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["design loads", "wind load", "dead load", "live load", "imposed load", "wind speed", "terrain category", "structural stability"],
    is_verified: true
  },
  {
    standard_number: "IS 516:2021",
    title: "Hardened Concrete - Methods of Test",
    scope: "Covers methods of test for strength of concrete: compressive strength, flexural strength, splitting tensile strength, modulus of elasticity, and pull-out test on hardened concrete specimens.",
    description: "The fundamental testing standard used in every construction testing laboratory across India to verify whether concrete meets specified target grades.",
    category: "Civil Engineering",
    industry: "Testing & Quality Assurance",
    technical_committee: "CED 2 (Cement and Concrete Sectional Committee)",
    publication_year: 2021,
    revision_information: "Revised & split into parts (Part 1/Sec 1 Compressive, Flexural and Split Tensile)",
    amendments: "Updated testing machine calibration tolerances and loading rates",
    related_standards: ["IS 456", "IS 1199", "IS 10262"],
    certification_information: "Essential test procedure for NABL-accredited civil testing laboratories and BIS third-party surveillance.",
    testing_information: "Specifies cube compression machine loading rate of 14 MPa/min, specimen curing in water tank at 27±2°C for 28 days.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["concrete testing", "compressive strength", "cube test", "flexural strength", "split tensile", "modulus of elasticity"],
    is_verified: true
  },
  {
    standard_number: "IS 4031:1988",
    title: "Methods of Physical Tests for Hydraulic Cement",
    scope: "Covers standard laboratory test methods for hydraulic cements across multiple parts: Part 1 (Fineness by dry sieving), Part 2 (Blaine fineness), Part 3 (Normal consistency), Part 4 (Initial and final setting times), Part 5 (Soundness by Le Chatelier), and Part 6 (Compressive strength).",
    description: "The standard testing procedure battery required to certify all ordinary portland cement, blended cement, and slag cement in India.",
    category: "Civil Engineering",
    industry: "Cement & Testing",
    technical_committee: "CED 2 (Cement and Concrete Sectional Committee)",
    publication_year: 1988,
    revision_information: "Reaffirmed 2019 (Various parts updated)",
    amendments: "Incorporates Vicat apparatus digital gauge tolerances and standard Ennore sand mortar ratio (1:3)",
    related_standards: ["IS 269", "IS 8112", "IS 12269", "IS 1489", "IS 650"],
    certification_information: "Mandatory qualification test required for every batch released by cement plants under BIS License.",
    testing_information: "Setting time with Vicat apparatus (initial min 30 min, final max 600 min), Le-Chatelier expansion max 10 mm, compressive mortar strength.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["cement testing", "fineness", "blaine air permeability", "setting time", "soundness", "le chatelier", "vicat needle"],
    is_verified: true
  },
  {
    standard_number: "IS 1893 (Part 1):2016",
    title: "Criteria for Earthquake Resistant Design of Structures - Part 1: General Provisions and Buildings",
    scope: "Deals with assessment of seismic loads on buildings and structures in India. Classifies India into seismic zones II, III, IV, and V, and specifies response spectra, importance factors, response reduction factors (R), and dynamic analysis procedures.",
    description: "The statutory seismic code in India applied to ensure buildings and civil structures withstand earthquake forces without collapse.",
    category: "Civil Engineering",
    industry: "Structural Safety & Geotechnical",
    technical_committee: "CED 39 (Earthquake Engineering Sectional Committee)",
    publication_year: 2016,
    revision_information: "Sixth Revision 2016",
    amendments: "Amendment 1 & 2 incorporated; enhanced zone factors (Z) and torsional irregularity checks",
    related_standards: ["IS 13920", "IS 456", "IS 800", "IS 875"],
    certification_information: "Statutory requirement under building bylaws and State Disaster Management Authorities.",
    testing_information: "Response spectrum analysis, modal mass participation minimum 90%, and story drift limitation (0.004 times story height).",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["earthquake", "seismic design", "seismic zone", "zone factor", "response spectrum", "story drift", "base shear", "ductility"],
    is_verified: true
  },
  {
    standard_number: "IS 13920:2016",
    title: "Ductile Design and Detailing of Reinforced Concrete Structures Subjected to Seismic Forces - Code of Practice",
    scope: "Covers the requirements for designing and detailing of monolithic reinforced concrete building structures to impart adequate ductility when subjected to seismic forces in Zones III, IV, and V.",
    description: "Mandatory detailing standard ensuring reinforced concrete beams, columns, beam-column joints, and shear walls possess ductile plastic deformation capacity.",
    category: "Civil Engineering",
    industry: "Structural Safety",
    technical_committee: "CED 39 (Earthquake Engineering Sectional Committee)",
    publication_year: 2016,
    revision_information: "First Revision 2016",
    amendments: "Comprehensive overhaul addressing soft storeys, column-beam capacity ratios, and confinement hoop spacings",
    related_standards: ["IS 456", "IS 1893", "IS 1786"],
    certification_information: "Mandatory compliance for all residential, commercial, and public RCC multi-storey buildings in seismic zones III, IV, and V.",
    testing_information: "Specifies 135-degree hooks on stirrups with 10-diameter extension, closely spaced confining reinforcement in joint regions.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["ductile detailing", "seismic detailing", "stirrup spacing", "beam column joint", "shear wall", "confinement"],
    is_verified: true
  },
  {
    standard_number: "IS 269:2015",
    title: "Ordinary Portland Cement - Specification",
    scope: "Covers the manufacture, chemical and physical requirements of 33, 43, and 53 grade ordinary Portland cement (harmonized into a single comprehensive standard).",
    description: "The core product specification for all ordinary Portland cement manufactured and marketed in India.",
    category: "Civil Engineering",
    industry: "Cement & Building Materials",
    technical_committee: "CED 2 (Cement and Concrete Sectional Committee)",
    publication_year: 2015,
    revision_information: "Sixth Revision 2015 (Merged IS 269:1989, IS 8112:1989, and IS 12269:1987)",
    amendments: "Permits addition of performance improvers up to 5 percent",
    related_standards: ["IS 4031", "IS 4032", "IS 456"],
    certification_information: "Mandatory ISI Certification mark under Cement (Quality Control) Order. No cement can be sold in India without BIS Licence.",
    testing_information: "Tested for fineness (min 225 m2/kg), 28-day compressive strength (33, 43, or 53 MPa minimum), and insoluble residue max 4%.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["cement", "ordinary portland cement", "OPC 53", "OPC 43", "OPC 33", "clinker", "gypsum", "compressive strength"],
    is_verified: true
  },
  {
    standard_number: "IS 1489 (Part 1):2015",
    title: "Portland Pozzolana Cement - Specification - Part 1: Fly Ash Based",
    scope: "Covers the manufacture and chemical and physical requirements of Portland Pozzolana cement using fly ash pozzolana.",
    description: "National standard for environmentally sustainable green cement produced using pulverized fuel ash (fly ash) from thermal power plants.",
    category: "Civil Engineering",
    industry: "Cement & Building Materials",
    technical_committee: "CED 2 (Cement and Concrete Sectional Committee)",
    publication_year: 2015,
    revision_information: "Third Revision 2015",
    amendments: "Permissible fly ash addition range specified between 15% and 35%",
    related_standards: ["IS 3812", "IS 4031", "IS 4032", "IS 456"],
    certification_information: "Mandatory ISI Certification under Cement QCO.",
    testing_information: "Tested for soundness (Le Chatelier max 10mm, autoclave max 0.8%), setting time, and 28-day compressive strength (min 33 MPa).",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["PPC", "portland pozzolana cement", "fly ash", "green cement", "thermal power ash", "hydraulic cement"],
    is_verified: true
  },
  {
    standard_number: "IS 3043:2018",
    title: "Code of Practice for Earthing",
    scope: "Provides guidelines on the design, installation, testing and maintenance of electrical earthing systems in AC systems up to and including 33 kV for protection of human life and equipment.",
    description: "The primary electrical safety code in India for grounding and earthing of residential, commercial, and heavy industrial electrical installations.",
    category: "Electrical Engineering",
    industry: "Power & Electrical Safety",
    technical_committee: "ETD 20 (Electrical Installation Sectional Committee)",
    publication_year: 2018,
    revision_information: "First Revision 2018",
    amendments: "Updated to align with IEC 60364 series and Central Electricity Authority (CEA) Safety Regulations",
    related_standards: ["IS 732", "IS 694", "IS 2309"],
    certification_information: "Statutory requirement under Central Electricity Authority (Measures relating to Safety and Electric Supply) Regulations.",
    testing_information: "Earth resistance measurement using Earth Resistance Tester (Wenner 4-pin method or fall of potential method), step and touch potential calculations.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["earthing", "grounding", "earth resistance", "earth electrode", "fault current", "step potential", "touch potential", "earth pit"],
    is_verified: true
  },
  {
    standard_number: "IS 732:2019",
    title: "Code of Practice for Electrical Wiring Installations",
    scope: "Covers the design, selection, erection, inspection and testing of electrical wiring installations operating at voltages up to and including 1000 V AC or 1500 V DC.",
    description: "Comprehensive national electrical code for all residential, commercial, institutional, and industrial building wiring installations.",
    category: "Electrical Engineering",
    industry: "Building Services & Electrical",
    technical_committee: "ETD 20 (Electrical Installation Sectional Committee)",
    publication_year: 2019,
    revision_information: "Fourth Revision 2019",
    amendments: "Harmonized with IEC 60364 with emphasis on Residual Current Devices (RCD/ELCB) protection",
    related_standards: ["IS 3043", "IS 694", "IS 12640", "IS 8828"],
    certification_information: "Mandatory compliance for issuing Electrical Inspectorate occupancy safety certificates.",
    testing_information: "Insulation resistance testing (min 1 Megohm at 500V DC), earth continuity verification, and polarity check of switches.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["wiring", "electrical installation", "conduit", "circuit breaker", "RCD", "distribution board", "insulation resistance"],
    is_verified: true
  },
  {
    standard_number: "IS 694:2010",
    title: "Polyvinyl Chloride Insulated Unsheathed and Sheathed Cables/Cords with Rigid and Flexible Conductor for Working Voltages up to and Including 450/750 V",
    scope: "Specifies requirements for PVC insulated single core and multicore unsheathed and sheathed cables with copper or aluminium conductors used for electric power and lighting.",
    description: "The standard for domestic house wires and flexible cables found in homes and commercial complexes across India.",
    category: "Electrical Engineering",
    industry: "Cables & Conductors",
    technical_committee: "ETD 9 (Power Cables Sectional Committee)",
    publication_year: 2010,
    revision_information: "Fourth Revision, Reaffirmed 2020",
    amendments: "Includes Flame Retardant (FR) and Flame Retardant Low Smoke (FRLS) insulation categories",
    related_standards: ["IS 8130", "IS 5831", "IS 10810"],
    certification_information: "Mandatory ISI Certification under Electrical Wires and Cables QCO.",
    testing_information: "Conductor resistance (IS 8130), spark test, insulation resistance, high voltage test in water, and oxygen index/temperature index for FR cables.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["house wire", "copper cable", "PVC insulation", "FRLS", "flame retardant", "conductor resistance", "spark test"],
    is_verified: true
  },
  {
    standard_number: "IS 1293:2019",
    title: "Plugs and Socket-Outlets for Domestic and Similar Purposes of Rated Voltage up to and Including 250 V and Rated Current up to and Including 16 A - Specification",
    scope: "Applies to plugs and fixed or portable socket-outlets for AC only, with or without earthing contact, with rated voltage up to 250 V and rated current up to 16 A intended for household and commercial use.",
    description: "National standard governing Indian 2-pin and 3-pin round pin plugs and socket outlets (6A and 16A configurations).",
    category: "Electrical Engineering",
    industry: "Consumer Electronics & Appliances",
    technical_committee: "ETD 14 (Electrical Accessories Sectional Committee)",
    publication_year: 2019,
    revision_information: "Fourth Revision 2019",
    amendments: "Introduced shuttered sockets and revised temperature rise limits during continuous 16A load",
    related_standards: ["IS 302", "IS 3854"],
    certification_information: "Mandatory ISI Mark certification under Plugs and Socket Outlets QCO (DPIIT).",
    testing_information: "Withdrawal force test, temperature rise test (<45K), insulation resistance, endurance test (10,000 operations), and glow wire test at 850°C.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["plug", "socket", "switch socket", "power plug 16A", "3-pin plug", "earthing pin", "glow wire test"],
    is_verified: true
  },
  {
    standard_number: "IS 13252 (Part 1):2010",
    title: "Information Technology Equipment - Safety - Part 1: General Requirements",
    scope: "Applicable to mains-powered or battery-powered information technology equipment, including electrical business equipment and associated equipment, with a rated voltage not exceeding 600 V.",
    description: "The core safety standard for laptops, smartphones, servers, printers, displays, power adapters, and networking hardware under the Compulsory Registration Scheme (CRS).",
    category: "Electronics",
    industry: "Information Technology & Hardware",
    technical_committee: "LITD 8 (Audio, Video and IT Equipment Sectional Committee)",
    publication_year: 2010,
    revision_information: "Second Edition (Aligned with IEC 60950-1), Reaffirmed 2020",
    amendments: "Incorporates Amendments 1 and 2",
    related_standards: ["IS/IEC 62368-1", "IS 16046"],
    certification_information: "Mandatory Registration under BIS Compulsory Registration Scheme (CRS) administered by MeitY.",
    testing_information: "Electric strength test, leakage current test, temperature rise of components under fault conditions, clearance and creepage distance measurements.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["IT equipment", "laptop safety", "mobile phone safety", "power adapter", "CRS", "MeitY", "leakage current", "creepage"],
    is_verified: true
  },
  {
    standard_number: "IS 16046 (Part 1 & 2):2018",
    title: "Secondary Cells and Batteries Containing Alkaline or Other Non-Acid Electrolytes - Safety Requirements for Portable Sealed Secondary Cells",
    scope: "Part 1 covers nickel systems; Part 2 covers lithium systems for use in portable electronic applications such as smartphones, laptops, power banks, and tablets.",
    description: "Crucial battery safety standard safeguarding consumers from fire, explosion, and thermal runaway hazards in lithium-ion batteries.",
    category: "Electronics",
    industry: "Battery & Consumer Tech",
    technical_committee: "ETD 11 (Secondary Cells and Batteries Sectional Committee)",
    publication_year: 2018,
    revision_information: "Harmonized with IEC 62133-1 and IEC 62133-2",
    amendments: "Strict internal short-circuit and overcharging testing requirements",
    related_standards: ["IS 13252", "IS/IEC 62368-1"],
    certification_information: "Mandatory BIS CRS registration required before any smartphone, laptop, or power bank battery can be imported or sold in India.",
    testing_information: "Continuous charging, external short circuit at 55°C, thermal abuse test (130°C for 10 min), crush test, and forced discharge test.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["lithium ion battery", "battery safety", "power bank", "thermal runaway", "overcharging test", "cell safety", "CRS"],
    is_verified: true
  },
  {
    standard_number: "IS 10500:2012",
    title: "Drinking Water - Specification",
    scope: "Prescribes the quality requirements for drinking water meant for human consumption. Defines acceptable and permissible limits for organoleptic, physical, chemical, toxic, and bacteriological parameters.",
    description: "The national benchmark in India for potable tap water and treated municipal drinking water supplied to citizens.",
    category: "Food & Water",
    industry: "Public Health & Water Supply",
    technical_committee: "FAD 25 (Drinking Water Sectional Committee)",
    publication_year: 2012,
    revision_information: "Second Revision, Reaffirmed 2018",
    amendments: "Amendments 1 to 3 with stringent limits on pesticide residues, arsenic (<0.01 mg/l), fluoride (<1.0 mg/l), and heavy metals",
    related_standards: ["IS 3025", "IS 1622", "IS 14543"],
    certification_information: "Enforced across Jal Jeevan Mission (JJM), municipal corporations, and food safety audits (FSSAI).",
    testing_information: "Testing for turbidity, pH (6.5 to 8.5), total dissolved solids (TDS max 500 mg/l), heavy metals by ICP-MS, and E. coli detection per IS 1622.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["drinking water", "potable water", "TDS", "arsenic", "fluoride", "coliform", "water testing", "heavy metals", "Jal Jeevan"],
    is_verified: true
  },
  {
    standard_number: "IS 14543:2016",
    title: "Packaged Drinking Water (Other than Packaged Natural Mineral Water) - Specification",
    scope: "Prescribes the requirements and methods of sampling and test for packaged drinking water, other than packaged natural mineral water, meant for direct consumption in sealed containers.",
    description: "Mandatory standard for bottled water jars and PET bottles sold under commercial brand names across India.",
    category: "Food & Water",
    industry: "Packaged Food & Beverages",
    technical_committee: "FAD 25 (Drinking Water Sectional Committee)",
    publication_year: 2016,
    revision_information: "Second Revision 2016",
    amendments: "Includes standards for remineralization and food-grade packaging material testing",
    related_standards: ["IS 10500", "IS 13428", "IS 15410"],
    certification_information: "Mandatory ISI Certification Scheme I under FSSAI regulations. No packaged water can be bottled or sold without BIS license.",
    testing_information: "Daily microbiological testing (Zero Coliform, Zero Pseudomonas aeruginosa, Zero yeast/mould in 250ml), total dissolved solids, ozone residue test.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["packaged drinking water", "bottled water", "mineral water", "water jar", "reverse osmosis", "ozone disinfection", "coliform free"],
    is_verified: true
  },
  {
    standard_number: "IS 13428:2005",
    title: "Packaged Natural Mineral Water - Specification",
    scope: "Specifies requirements for packaged natural mineral water obtained directly from natural subterranean sources such as springs, boreholes or wells without chemical treatment.",
    description: "Strict standard for naturally sourced spring and mineral waters, guaranteeing natural chemical equilibrium and microbiological purity.",
    category: "Food & Water",
    industry: "Packaged Beverages",
    technical_committee: "FAD 25 (Drinking Water Sectional Committee)",
    publication_year: 2005,
    revision_information: "Second Revision, Reaffirmed 2019",
    amendments: "Amendments 1 to 4 incorporated",
    related_standards: ["IS 14543", "IS 10500", "IS 3025"],
    certification_information: "Mandatory ISI Mark under Food Safety and Standards Act (FSSAI).",
    testing_information: "Testing at source for mineral balance, dry residue at 180°C, radioactivity testing, and pathogen absence in 250ml.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["natural mineral water", "spring water", "groundwater purity", "artesian well", "FSSAI", "ISI certification"],
    is_verified: true
  },
  {
    standard_number: "IS 2189:2008",
    title: "Selection, Installation and Maintenance of Automatic Fire Detection and Alarm System - Code of Practice",
    scope: "Covers the planning, design, installation, commissioning and maintenance of fire detection and alarm systems in and around buildings.",
    description: "The national standard for smoke detectors, heat detectors, manual call points, and fire alarm control panels (FACP) in public and industrial premises.",
    category: "Safety & Fire Protection",
    industry: "Fire Safety & Building Automation",
    technical_committee: "CED 22 (Fire Fighting Sectional Committee)",
    publication_year: 2008,
    revision_information: "Third Revision, Reaffirmed 2019",
    amendments: "Updated for addressable fire alarm loops and multi-sensor detectors",
    related_standards: ["IS 3844", "IS 15683", "IS 15908"],
    certification_information: "Mandatory requirement for issuing Fire No Objection Certificate (Fire NOC) by State Fire Services.",
    testing_information: "Audibility sound level check (>65 dBA throughout building, >75 dBA at bedhead), optical smoke chamber response threshold testing.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["fire alarm", "smoke detector", "fire detection", "FACP", "manual call point", "hooter", "fire safety", "Fire NOC"],
    is_verified: true
  },
  {
    standard_number: "IS 15683:2018",
    title: "Portable Fire Extinguishers - Performance and Construction - Specification",
    scope: "Specifies requirements for design, construction and performance of portable fire extinguishers of water, foam, dry powder, clean agent, and carbon dioxide types.",
    description: "Governs all red portable fire extinguishers installed in offices, schools, vehicles, hospitals, and industrial plants across India.",
    category: "Safety & Fire Protection",
    industry: "Fire Fighting Equipment",
    technical_committee: "CED 22 (Fire Fighting Sectional Committee)",
    publication_year: 2018,
    revision_information: "First Revision 2018",
    amendments: "Harmonized fire ratings for Class A, B, C, D, and F/K (kitchen fires)",
    related_standards: ["IS 2190", "IS 2189"],
    certification_information: "Mandatory ISI Certification Mark (Scheme I) under Fire Extinguisher Quality Control Order.",
    testing_information: "Hydrostatic pressure burst test (pressure up to 3 times working pressure), discharge duration test, electrical conductivity test, and fire rating crib extinguishment tests.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["fire extinguisher", "ABC powder", "CO2 extinguisher", "fire rating", "hydrostatic test", "fire safety", "discharge time"],
    is_verified: true
  },
  {
    standard_number: "IS 4151:2015",
    title: "Protective Helmets for Two Wheeler Riders - Specification",
    scope: "Covers the requirements regarding material, construction, workmanship, finish and performance of protective helmets with or without lower face cover for two wheeler riders.",
    description: "Crucial consumer life-safety standard for all motorcycle and scooter riding helmets manufactured and sold in India.",
    category: "Consumer Products",
    industry: "Automotive Safety & Gear",
    technical_committee: "TED 26 (Automotive Safety Sectional Committee)",
    publication_year: 2015,
    revision_information: "Fourth Revision 2015",
    amendments: "Max weight restricted to 1.2 kg to reduce cervical strain and mandatory visor optical clarity norms",
    related_standards: ["IS 9980", "IS 7692"],
    certification_information: "Mandatory ISI certification under Ministry of Road Transport and Highways (MoRTH) QCO. Riding with non-ISI helmet is legally punishable.",
    testing_information: "Shock absorption impact test at ambient/hot/cold temperatures, retention system dynamic displacement test, chin strap strength test, and visor penetration test.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["helmet", "two wheeler helmet", "rider safety", "motorcycle helmet", "ISI helmet", "impact test", "chin strap", "MoRTH"],
    is_verified: true
  },
  {
    standard_number: "IS 9873 (Part 1 to 9):2019",
    title: "Safety of Toys - Safety Aspects Related to Mechanical and Physical Properties",
    scope: "Specifies acceptable criteria for the physical and mechanical properties of toys for children including small parts choking hazards, sharp edges, flammability, and toxic heavy metal migration.",
    description: "The comprehensive child safety standard in India preventing choking, chemical poisoning, and physical injuries from toys.",
    category: "Consumer Products",
    industry: "Toy Manufacturing & Child Safety",
    technical_committee: "PCD 14 (Toys Sectional Committee)",
    publication_year: 2019,
    revision_information: "Aligned with ISO 8124 series",
    amendments: "Strict phthalate plasticizer limits (<0.1%) and toxic element migration testing",
    related_standards: ["IS 15644", "IS 9873 Part 2 (Flammability)", "IS 9873 Part 3 (Chemical migration)"],
    certification_information: "Mandatory BIS Certification (Scheme I) under Toys (Quality Control) Order. No toys can be sold or imported without BIS ISI License.",
    testing_information: "Drop test, torque and tension test on small parts, cylinder gauge test (choking hazard), flame spread rate, and migration of 8 elements (lead, cadmium, mercury, etc.) by ICP-OES.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["toy safety", "child safety", "choking hazard", "phthalates", "toxic metals", "lead in toys", "ISI mark on toys"],
    is_verified: true
  },
  {
    standard_number: "IS 1239 (Part 1 & 2):2004",
    title: "Steel Tubes, Tubulars and Other Wrought Steel Fittings - Part 1: Steel Tubes",
    scope: "Covers the requirements for hot-finished seamless, electric resistance welded (ERW) and induction welded steel tubes for water, gas, steam and air lines in light, medium and heavy classes.",
    description: "The primary standard for galvanized iron (GI) pipes and black steel tubes used in plumbing, fire fighting pipelines, and HVAC systems.",
    category: "Mechanical Engineering",
    industry: "Pipes & Plumbing",
    technical_committee: "MTD 19 (Steel Tubes, Pipes and Fittings Sectional Committee)",
    publication_year: 2004,
    revision_information: "Sixth Revision, Reaffirmed 2019",
    amendments: "Amendments 1 to 5 incorporated",
    related_standards: ["IS 4736", "IS 1608"],
    certification_information: "Mandatory ISI mark under Steel and Steel Products QCO.",
    testing_information: "Hydrostatic test at 5 MPa without leakage, flattening test, cold bend test, and zinc coating mass test (min 360 g/m2 for galvanized tubes).",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["GI pipe", "steel tube", "ERW pipe", "plumbing pipe", "galvanizing", "hydrostatic test", "fire fighting pipe"],
    is_verified: true
  },
  {
    standard_number: "IS 302 (Part 1):2008",
    title: "Safety of Household and Similar Electrical Appliances - Part 1: General Requirements",
    scope: "Deals with the safety of electrical appliances for household and similar purposes, their rated voltage being not more than 250 V for single-phase appliances and 480 V for other appliances.",
    description: "The overarching electrical appliance safety standard covering irons, water heaters (geysers), mixers, toasters, and room heaters.",
    category: "Consumer Products",
    industry: "Home Appliances",
    technical_committee: "ETD 32 (Electrical Appliances Sectional Committee)",
    publication_year: 2008,
    revision_information: "Harmonized with IEC 60335-1",
    amendments: "Amendments 1 to 4 incorporated",
    related_standards: ["IS 302-2-3 (Electric irons)", "IS 302-2-21 (Storage water heaters)", "IS 1293"],
    certification_information: "Mandatory ISI Mark certification under Electrical Appliances QCO.",
    testing_information: "Electric strength test, leakage current and moisture resistance, abnormal operation heating test, earth resistance of appliance chassis (<0.1 ohm).",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["appliances safety", "geyser", "electric iron", "food mixer", "heating appliance", "ISI mark geyser", "leakage current"],
    is_verified: true
  },
  {
    standard_number: "IS 1608 (Part 1):2018",
    title: "Metallic Materials - Tensile Testing - Part 1: Method of Test at Room Temperature",
    scope: "Specifies the method for tensile testing of metallic materials and defines the mechanical properties which can be determined at room temperature (yield strength, proof strength, tensile strength, elongation).",
    description: "The universal benchmark test in metallurgy and mechanical engineering for determining strength, elongation, and ductility of steel, aluminium, and brass specimens.",
    category: "Mechanical Engineering",
    industry: "Metallurgy & Material Testing",
    technical_committee: "MTD 3 (Mechanical Testing of Metals Sectional Committee)",
    publication_year: 2018,
    revision_information: "Fourth Revision (Aligned with ISO 6892-1)",
    amendments: "Updated strain rate control methods (Method A and Method B)",
    related_standards: ["IS 1786", "IS 2062", "IS 1599"],
    certification_information: "Fundamental reference test invoked in dozens of BIS product specifications.",
    testing_information: "Universal Testing Machine (UTM) testing with extensometer measuring 0.2% offset proof stress, peak tensile load, and percentage elongation after fracture.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["tensile testing", "metallic materials", "UTM", "yield strength", "proof stress", "elongation", "ductility", "tensile strength"],
    is_verified: true
  },
  {
    standard_number: "IS 1180 (Part 1):2014",
    title: "Outdoor Type Oil Immersed Distribution Transformers up to and Including 2500 kVA, 33 kV - Specification",
    scope: "Covers standard requirements and energy efficiency star levels for outdoor oil-immersed three-phase distribution transformers used in power distribution networks.",
    description: "Critical electrical infrastructure standard governing the efficiency, losses, and safety of electrical transformers on street utility poles.",
    category: "Electrical Engineering",
    industry: "Power Distribution",
    technical_committee: "ETD 16 (Transformers Sectional Committee)",
    publication_year: 2014,
    revision_information: "First Revision 2014",
    amendments: "Mandates Energy Efficiency Level 1, 2, and 3 loss ceilings aligned with BEE star ratings",
    related_standards: ["IS 2026", "IS 335 (Transformer oil)"],
    certification_information: "Mandatory ISI mark under Transformers (Quality Control) Order.",
    testing_information: "Measurement of no-load loss and load loss at 75°C, winding resistance, insulation resistance, lightning impulse test, and temperature rise test.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["transformer", "distribution transformer", "energy efficiency", "oil immersed", "BEE star rating", "loss measurement", "substation"],
    is_verified: true
  },
  {
    standard_number: "IS 8828:1996",
    title: "Electrical Accessories - Circuit-Breakers for Overcurrent Protection for Household and Similar Installations (MCB)",
    scope: "Applies to AC air-break miniature circuit-breakers (MCBs) for operation at 50 Hz, with a rated voltage not exceeding 440 V and rated current not exceeding 125 A, and breaking capacity up to 25,000 A.",
    description: "Standard for Miniature Circuit Breakers (MCBs) found in every household electrical distribution board.",
    category: "Electrical Engineering",
    industry: "Switchgear & Protection",
    technical_committee: "ETD 14 (Electrical Accessories Sectional Committee)",
    publication_year: 1996,
    revision_information: "Reaffirmed 2018 (Aligned with IEC 60898-1)",
    amendments: "Tripping characteristics B, C, and D curve standardized",
    related_standards: ["IS 732", "IS 12640", "IS 13947"],
    certification_information: "Mandatory ISI mark under Electrical Accessories QCO.",
    testing_information: "Short-circuit breaking capacity test (e.g. 10 kA), thermal tripping test at 1.13 and 1.45 times rated current, mechanical endurance (20,000 cycles).",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["MCB", "circuit breaker", "overcurrent protection", "short circuit", "distribution board", "tripping curve", "breaking capacity"],
    is_verified: true
  },
  {
    standard_number: "IS 12640 (Part 1 & 2):2016",
    title: "Residual Current Operated Circuit-Breakers (RCCB / ELCB) - Specification",
    scope: "Specifies residual current circuit-breakers without integral overcurrent protection (RCCBs) and with overcurrent protection (RCBOs) for household installations to prevent fatal electric shocks and electrical fire hazards.",
    description: "The life-saving electrical device standard that instantly trips power upon human contact with a live wire or current leakage (>30 mA).",
    category: "Electrical Engineering",
    industry: "Electrical Protection",
    technical_committee: "ETD 14 (Electrical Accessories Sectional Committee)",
    publication_year: 2016,
    revision_information: "Harmonized with IEC 61008-1",
    amendments: "Amendments for Type A and Type AC residual current characteristics",
    related_standards: ["IS 732", "IS 3043", "IS 8828"],
    certification_information: "Mandatory safety requirement under Central Electricity Authority Regulations for all domestic installations.",
    testing_information: "Residual operating current threshold (tripping at <= 30 mA within 40 ms), electrical endurance, and surge test.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["RCCB", "ELCB", "RCBO", "earth leakage", "electric shock prevention", "residual current", "30mA trip"],
    is_verified: true
  },
  {
    standard_number: "IS 1448:2018",
    title: "Methods of Test for Petroleum and Its Products",
    scope: "Comprehensive compendium of standard test methods for petroleum fuels, lubricating oils, greases, bitumens, and liquid petroleum gases (flash point, kinematic viscosity, octane number, cetane number, sulphur content).",
    description: "The standard testing bible for oil refineries, automotive fuels, and petroleum testing laboratories across India.",
    category: "Chemical",
    industry: "Petroleum & Energy",
    technical_committee: "PCD 1 (Petroleum and Petroleum Products Sectional Committee)",
    publication_year: 2018,
    revision_information: "Continuously maintained multi-part standard",
    amendments: "Updated to support BS-VI emission fuel testing protocols (10 ppm ultra-low sulphur)",
    related_standards: ["IS 2796 (Motor gasoline)", "IS 1460 (Diesel fuel)"],
    certification_information: "Referenced by Petroleum and Explosives Safety Organization (PESO) and MoP&NG.",
    testing_information: "Pensky-Martens closed cup flash point, Saybolt/Kinematic viscosity at 40°C/100°C, UV fluorescence sulphur determination.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["petroleum", "diesel", "petrol", "flash point", "viscosity", "octane", "sulphur test", "BS-VI", "lubricant"],
    is_verified: true
  },
  {
    standard_number: "IS 2796:2017",
    title: "Motor Gasoline - Specification (Petrol)",
    scope: "Prescribes the requirements and methods of sampling and test for motor gasoline for use in spark-ignition engines including BS-VI unleaded gasoline and ethanol blended petrol (E10, E20).",
    description: "The national standard for automotive petrol sold at fuel retail dispensing stations in India.",
    category: "Chemical",
    industry: "Automotive Fuel",
    technical_committee: "PCD 1 (Petroleum and Petroleum Products Sectional Committee)",
    publication_year: 2017,
    revision_information: "Fifth Revision (BS-VI grade with max 10 mg/kg sulphur)",
    amendments: "Added specifications for E20 (20% ethanol blend)",
    related_standards: ["IS 1448", "IS 15464"],
    certification_information: "Mandatory fuel standard under Ministry of Petroleum and Natural Gas notifications.",
    testing_information: "Research Octane Number (RON min 91), sulphur content max 10 ppm, distillation recovery temperatures, benzene content max 1% vol.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["petrol", "motor gasoline", "RON 91", "BS-VI", "ethanol blend", "E20", "sulphur limit", "spark ignition"],
    is_verified: true
  },
  {
    standard_number: "IS 1460:2017",
    title: "Automotive Diesel Fuel - Specification",
    scope: "Prescribes requirements and test methods for automotive diesel fuel intended for use in high speed automotive diesel engines (commercial vehicles, buses, passenger cars, generators).",
    description: "The national standard for high-speed diesel (HSD) conforming to strict BS-VI environmental norms.",
    category: "Chemical",
    industry: "Automotive Fuel & Transport",
    technical_committee: "PCD 1 (Petroleum and Petroleum Products Sectional Committee)",
    publication_year: 2017,
    revision_information: "Fifth Revision 2017 (BS-VI)",
    amendments: "Max 10 mg/kg sulphur ceiling and minimum 51 cetane number",
    related_standards: ["IS 1448", "IS 15607 (Biodiesel)"],
    certification_information: "Enforced at all fuel refineries and transport depots.",
    testing_information: "Cetane index/number (min 51), flash point Abel (min 35°C), density at 15°C, cold filter plugging point (CFPP) for winter grades.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["diesel", "HSD", "cetane number", "BS-VI diesel", "ultra low sulphur", "flash point", "automotive fuel"],
    is_verified: true
  },
  {
    standard_number: "IS 1570 (Part 1 to 5):1988",
    title: "Schedules for Wrought Steels for General Engineering Purposes",
    scope: "Contains schedules of compositions and tensile properties for wrought carbon, carbon-manganese, alloy and stainless steels used in machinery, automotive crankshafts, gears, and fasteners.",
    description: "Standard metallurgical reference in India defining chemical compositions and mechanical properties of engineering alloy steels (e.g. En series, 40Cr4Mo2, C45).",
    category: "Mechanical Engineering",
    industry: "Manufacturing & Metallurgy",
    technical_committee: "MTD 4 (Wrought Steels Sectional Committee)",
    publication_year: 1988,
    revision_information: "Reaffirmed 2019",
    amendments: "Harmonized designations with unified numbering systems",
    related_standards: ["IS 2062", "IS 1608", "IS 1500"],
    certification_information: "OEM automotive and precision component manufacturing specification standard.",
    testing_information: "Hardenability Jominy end-quench test, chemical spectrometer analysis, Brinell hardness per IS 1500.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["wrought steel", "alloy steel", "carbon steel", "C45", "En8", "En19", "case hardening", "jominy test", "automotive steel"],
    is_verified: true
  },
  {
    standard_number: "IS 7098 (Part 1 & 2):1988",
    title: "Crosslinked Polyethylene (XLPE) Insulated Thermoplastic Sheathed Cables",
    scope: "Part 1 covers cables for working voltages up to and including 1100 V; Part 2 covers cables for working voltages from 3.3 kV up to and including 33 kV for electric power transmission.",
    description: "The primary standard for heavy-duty underground power cables and medium-voltage power distribution networks in India.",
    category: "Electrical Engineering",
    industry: "Power Transmission & Cables",
    technical_committee: "ETD 9 (Power Cables Sectional Committee)",
    publication_year: 1988,
    revision_information: "Reaffirmed 2020",
    amendments: "Includes high heat deformation resistance and treeing retardant XLPE insulation",
    related_standards: ["IS 8130", "IS 5831", "IS 10810"],
    certification_information: "Mandatory ISI Certification under Power Cables QCO.",
    testing_information: "Partial discharge test, hot set test (elongation < 175%), high voltage AC withstand test for 4 hours, and impulse voltage withstand test.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["XLPE cable", "HT cable", "underground cable", "power distribution", "partial discharge", "hot set test", "armoured cable"],
    is_verified: true
  },
  {
    standard_number: "IS 14268:2017",
    title: "Low Relaxation Seven-Wire Uncoated Strand for Prestressed Concrete - Specification",
    scope: "Covers the requirements for low relaxation seven-wire high tensile steel strands for prestressed concrete work in nominal diameters from 9.3 mm to 15.7 mm.",
    description: "Specialized high-strength steel strands used inside post-tensioned ducts for flyovers, metro rail viaducts, and bridge construction.",
    category: "Civil Engineering",
    industry: "Prestressed Concrete & Infrastructure",
    technical_committee: "CED 54 (Concrete Reinforcement Sectional Committee)",
    publication_year: 2017,
    revision_information: "Second Revision 2017",
    amendments: "Specified maximum isothermal relaxation at 1000 hours not to exceed 2.5% at 70% initial load",
    related_standards: ["IS 1343", "IS 1608"],
    certification_information: "Mandatory ISI mark under Steel QCO. Audited rigorously by RDSO and NHAI.",
    testing_information: "1000-hour stress relaxation test, 0.2% proof load (minimum 88% of breaking force), breaking load, and total elongation at fracture.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["HT strand", "LRPC strand", "prestressed steel", "seven wire strand", "post tensioning", "relaxation test", "bridge cables"],
    is_verified: true
  },
  {
    standard_number: "IS 15410:2003",
    title: "Containers for Packaging of Natural Mineral Water and Packaged Drinking Water - Specification",
    scope: "Prescribes requirements for flexible and semi-rigid containers manufactured from food-grade plastics (PET, PC) intended for packaging drinking water.",
    description: "Guarantees that 20-litre water jars and PET bottles do not leach harmful microplastics or plasticizers into drinking water.",
    category: "Consumer Products",
    industry: "Plastics & Packaging",
    technical_committee: "PCD 21 (Plastics Packaging Sectional Committee)",
    publication_year: 2003,
    revision_information: "Reaffirmed 2018",
    amendments: "BPA extraction ceilings and overall migration test limits",
    related_standards: ["IS 14543", "IS 9845", "IS 10146"],
    certification_information: "Mandatory compliance for all licensed packaged drinking water bottling units.",
    testing_information: "Overall migration test in water/simulants (max 10 mg/dm2 or 60 mg/kg), drop impact test from 1.2 meters, and environmental stress crack resistance (ESCR).",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["PET bottle", "20 litre jar", "food grade plastic", "overall migration", "drop test", "packaging safety", "water bottle"],
    is_verified: true
  },
  {
    standard_number: "IS 1622:1981",
    title: "Methods of Sampling and Microbiological Examination of Water",
    scope: "Covers procedures for sampling water for bacteriological testing, and standard methods for detection and enumeration of coliform organisms, faecal streptococci, and pathogens in water supplies.",
    description: "The standard microbiological laboratory protocol across India for determining whether water is contaminated with sewage or disease-causing pathogens.",
    category: "Food & Water",
    industry: "Water Testing & Microbiology",
    technical_committee: "FAD 25 (Drinking Water Sectional Committee)",
    publication_year: 1981,
    revision_information: "Reaffirmed 2019",
    amendments: "Membrane filter technique and MPN (Most Probable Number) statistical tables standardized",
    related_standards: ["IS 10500", "IS 14543", "IS 13428"],
    certification_information: "Invoked by State Public Health Engineering Departments (PHED) and National Accreditation Board for Testing Laboratories (NABL).",
    testing_information: "MacConkey broth incubation at 37°C for total coliform and 44°C for thermotolerant faecal coliform (E. coli); membrane filtration method.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["water bacteriology", "coliform test", "E. coli", "MPN test", "membrane filtration", "pathogen test", "sewage contamination"],
    is_verified: true
  },
  {
    standard_number: "IS 2386 (Part 1 to 8):1963",
    title: "Methods of Test for Aggregates for Concrete",
    scope: "Covers methods for test for aggregate: Particle size and shape (Part 1), Estimation of deleterious materials and organic impurities (Part 2), Specific gravity, density and voids (Part 3), Mechanical properties including Crushing and Impact (Part 4), Soundness (Part 5), Measuring mortar making properties (Part 6), Alkali-aggregate reactivity (Part 7), and Petrographic examination (Part 8).",
    description: "The definitive testing standard for assessing the quality and soundness of crushed gravel, stone, and sand used in concrete.",
    category: "Civil Engineering",
    industry: "Testing & Construction",
    technical_committee: "CED 2 (Cement and Concrete Sectional Committee)",
    publication_year: 1963,
    revision_information: "Reaffirmed 2021",
    amendments: "Flakiness and elongation testing gauges recalibrated",
    related_standards: ["IS 383", "IS 456", "IS 516"],
    certification_information: "Mandatory qualification tests before opening quarry crushers for national highway and bridge projects.",
    testing_information: "Aggregate Impact Value (<30% for wearing surfaces), Aggregate Crushing Value, Los Angeles Abrasion, sodium sulphate soundness loss.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["aggregate testing", "flakiness index", "elongation index", "aggregate crushing value", "soundness test", "abrasion test", "quarry testing"],
    is_verified: true
  },
  {
    standard_number: "IS 13311 (Part 1 & 2):1992",
    title: "Methods of Non-Destructive Testing of Concrete",
    scope: "Part 1 covers Ultrasonic Pulse Velocity (UPV); Part 2 covers Rebound Hammer test on hardened concrete in structures without damaging structural integrity.",
    description: "The primary non-destructive testing (NDT) standard used by structural audit engineers to evaluate concrete quality, honeycombing, voids, and cracks in existing buildings.",
    category: "Civil Engineering",
    industry: "NDT & Structural Health Monitoring",
    technical_committee: "CED 2 (Cement and Concrete Sectional Committee)",
    publication_year: 1992,
    revision_information: "Reaffirmed 2018",
    amendments: "Standardized calibration anvil bounce criteria for Schmidt Rebound Hammer",
    related_standards: ["IS 456", "IS 516"],
    certification_information: "Mandatory methodology for structural stability audits of aged buildings required by municipal corporations.",
    testing_information: "Direct, semi-direct and indirect ultrasonic pulse velocity transmission (UPV > 4.5 km/sec indicates excellent concrete quality); Rebound number correlation curves.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["NDT", "non destructive testing", "rebound hammer", "ultrasonic pulse velocity", "UPV", "structural audit", "concrete cracks", "honeycombing"],
    is_verified: true
  },
  {
    standard_number: "IS 16102 (Part 1 & 2):2012",
    title: "Self-Ballasted LED Lamps for General Lighting Services - Safety and Performance Requirements",
    scope: "Covers the safety and performance requirements of self-ballasted LED lamps having a rated wattage up to 60 W and a rated voltage up to 250 V AC for domestic and similar lighting.",
    description: "National standard governing energy-saving LED light bulbs sold under consumer brands and distributed under government schemes like UJALA.",
    category: "Electronics",
    industry: "Lighting & Energy Efficiency",
    technical_committee: "ETD 23 (Electric Lamps and their Auxiliaries Sectional Committee)",
    publication_year: 2012,
    revision_information: "Harmonized with IEC 62560 and IEC 62612",
    amendments: "Strict lumen maintenance (L70 life > 25,000 hrs) and power factor (>0.90)",
    related_standards: ["IS 15885", "IS 16103"],
    certification_information: "Mandatory BIS CRS registration scheme and BEE Star Labelling Scheme.",
    testing_information: "Photometric lumen output in integrating sphere, color rendering index (CRI >= 80), insulation resistance, thermal endurance test.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["LED bulb", "LED lamp", "lighting safety", "lumen output", "power factor", "UJALA", "BEE star rating", "CRI"],
    is_verified: true
  },
  {
    standard_number: "IS 16018:2012",
    title: "Wheelbarrows and Hand Carts - Specification",
    scope: "Specifies constructional and dimensional requirements for metal wheelbarrows and two-wheel hand carts used for construction and agricultural transport.",
    description: "Standard for construction tools and material-handling carts used on building sites across India.",
    category: "Mechanical Engineering",
    industry: "Construction Equipment & Tools",
    technical_committee: "MED 7 (Material Handling Systems Sectional Committee)",
    publication_year: 2012,
    revision_information: "First Revision, Reaffirmed 2018",
    amendments: "Specifies pneumatic wheel rim gauges and anti-corrosive primer coating",
    related_standards: ["IS 2062", "IS 1239"],
    certification_information: "Standardized procurement specification for municipal sanitation and CPWD civil sites.",
    testing_information: "Static load test at 1.5 times rated capacity without permanent buckle or deformation of axle.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["wheelbarrow", "hand cart", "construction tools", "material handling", "civil site equipment"],
    is_verified: true
  },
  {
    standard_number: "IS 15652:2006",
    title: "Insulating Mats for Electrical Purposes - Specification",
    scope: "Prescribes requirements for electrical insulating mats made of elastomeric materials (rubber/polymers) for use as a floor covering near electrical apparatus for operator protection up to 33 kV.",
    description: "Mandatory electrical safety mats installed in front of substation panels, switchboards, and motor control centers to prevent electrocution.",
    category: "Electrical Engineering",
    industry: "Industrial Safety & Electrical",
    technical_committee: "ETD 18 (Industrial Process Measurement and Control Sectional Committee)",
    publication_year: 2006,
    revision_information: "Supercedes IS 5424 (Wooden duckboards), Reaffirmed 2018",
    amendments: "Defines Class A (up to 3.3 kV), Class B (up to 11 kV), and Class C (up to 33 kV)",
    related_standards: ["IS 3043", "IS 732"],
    certification_information: "Mandatory ISI mark under Safety Mats QCO. Inspected by Chief Electrical Inspectorate.",
    testing_information: "Dielectric proof test (withstand 10 kV to 45 kV AC without puncture), leakage current test, tensile strength, and flame retardancy.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["insulating mat", "electrical safety mat", "rubber mat", "switchboard mat", "dielectric test", "electrocution protection", "substation"],
    is_verified: true
  },
  {
    standard_number: "IS 1415:1989",
    title: "Electric Water Heaters - Specification",
    scope: "Covers stationary storage-type electric water heaters for household use, intended for heating water below boiling temperature.",
    description: "Standard for domestic electric geysers ensuring pressure relief, thermostat cut-off, and non-scalding safety.",
    category: "Consumer Products",
    industry: "Home Appliances",
    technical_committee: "ETD 32 (Electrical Appliances Sectional Committee)",
    publication_year: 1989,
    revision_information: "Reaffirmed 2019",
    amendments: "High pressure rating up to 8 bar for high-rise apartment compatibility",
    related_standards: ["IS 302-2-21", "IS 1293"],
    certification_information: "Mandatory ISI Certification mark under Electrical Appliances QCO.",
    testing_information: "Pressure test on inner tank (twice rated pressure, e.g. 1.6 MPa), thermal cut-out tripping, standing loss measurement for BEE Star Rating.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["geyser", "water heater", "electric geyser", "pressure relief valve", "thermostat", "storage water heater", "ISI geyser"],
    is_verified: true
  },
  {
    standard_number: "IS 2309:1989",
    title: "Protection of Buildings and Allied Structures Against Lightning - Code of Practice",
    scope: "Deals with the principles and guidelines for design, installation and maintenance of lightning protection systems on structures.",
    description: "National lightning conductor code protecting residential towers, industrial plants, and historical monuments from destructive lightning strikes.",
    category: "Electrical Engineering",
    industry: "Building Safety & Protection",
    technical_committee: "ETD 20 (Electrical Installation Sectional Committee)",
    publication_year: 1989,
    revision_information: "Second Revision, Reaffirmed 2019",
    amendments: "Incorporates rolling sphere method and down-conductor bonding requirements",
    related_standards: ["IS 3043", "IS/IEC 62305"],
    certification_information: "Mandatory compliance for high-rise building plans and petroleum storage depots.",
    testing_information: "Earthing resistance of lightning down conductor (< 10 ohms), air terminal cone of protection verification.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["lightning protection", "lightning arrestor", "down conductor", "air terminal", "rolling sphere method", "surge protection"],
    is_verified: true
  },
  {
    standard_number: "IS 4985:2021",
    title: "Unplasticized PVC Pipes for Potable Water Supplies - Specification",
    scope: "Specifies requirements for unplasticized polyvinyl chloride (uPVC) pipes intended for agricultural irrigation, potable water supply, and plumbing systems.",
    description: "The ubiquitous blue and white uPVC pipes widely used for underground drinking water lines and agricultural farm tubewells.",
    category: "Chemical & Polymers",
    industry: "Plumbing & Agriculture",
    technical_committee: "CED 50 (Plastic Piping System Sectional Committee)",
    publication_year: 2021,
    revision_information: "Fourth Revision 2021",
    amendments: "Eliminated lead-based heat stabilizers in favor of non-toxic calcium-zinc systems for safe drinking water",
    related_standards: ["IS 12235", "IS 10146"],
    certification_information: "Mandatory ISI mark under PVC Pipes QCO.",
    testing_information: "Short term hydrostatic pressure test (withstand burst at 4.2 times working pressure), 1000-hour sustained hydrostatic test, drop impact test at 0°C, and lead extraction test.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["uPVC pipe", "PVC pipe", "potable water pipe", "irrigation pipe", "lead free PVC", "hydrostatic burst", "plumbing pipe"],
    is_verified: true
  },
  {
    standard_number: "IS 12701:1996",
    title: "Rotational Moulded Polyethylene Water Storage Tanks - Specification",
    scope: "Specifies materials, dimensional tolerances, construction and performance requirements for rotational moulded polyethylene water storage tanks (overhead Sintex-style tanks) from 200 L to 20,000 L capacity.",
    description: "The national standard for black and white plastic rooftop water storage tanks installed on residential and commercial buildings across India.",
    category: "Civil Engineering",
    industry: "Water Storage & Polymers",
    technical_committee: "CED 50 (Plastic Piping System Sectional Committee)",
    publication_year: 1996,
    revision_information: "First Revision, Reaffirmed 2019",
    amendments: "Mandates UV carbon black compounding to prevent sunlight polymer degradation and algae growth",
    related_standards: ["IS 10146", "IS 9845"],
    certification_information: "Widely specified for CPWD, PWD, and municipal housing projects with ISI certification.",
    testing_information: "Flexural modulus of material, overall migration test for drinking water contact, impact test, and 100% full-water hydrostatic bulging test.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["water tank", "rooftop water tank", "sintex tank", "polyethylene tank", "rotational moulding", "UV stabilized", "drinking water storage"],
    is_verified: true
  },
  {
    standard_number: "IS 2190:2010",
    title: "Selection, Installation and Maintenance of First-Aid Fire Extinguishers - Code of Practice",
    scope: "Provides guidance on the selection, installation, distribution and maintenance of portable first-aid fire appliances in all classes of occupancies.",
    description: "Specifies where fire extinguishers must be mounted, the travel distance (max 15 meters), and mandatory periodic hydrostatic pressure testing cycles.",
    category: "Safety & Fire Protection",
    industry: "Fire Safety",
    technical_committee: "CED 22 (Fire Fighting Sectional Committee)",
    publication_year: 2010,
    revision_information: "Fourth Revision, Reaffirmed 2020",
    amendments: "Standardized refilling schedules and color-coding tags for annual inspection",
    related_standards: ["IS 15683", "IS 2189"],
    certification_information: "Mandatory compliance for factory safety audits under the Factories Act.",
    testing_information: "Quarterly inspection checklist, annual discharge testing, hydraulic pressure testing every 3 or 5 years.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["fire safety maintenance", "fire extinguisher placement", "fire audit", "maintenance of extinguishers", "fire drill"],
    is_verified: true
  },
  {
    standard_number: "IS 16047:2018",
    title: "Stationary Storage Batteries for Solar Photovoltaic Systems - Specification",
    scope: "Covers requirements and tests for stationary secondary lead-acid and lithium batteries for use with solar photovoltaic (SPV) systems.",
    description: "Standard for solar power backup batteries used in rural electrification, rooftop solar, and telecom towers.",
    category: "Electrical Engineering",
    industry: "Renewable Energy & Solar",
    technical_committee: "ETD 11 (Secondary Cells and Batteries Sectional Committee)",
    publication_year: 2018,
    revision_information: "Aligned with MNRE technical specifications",
    amendments: "Deep discharge endurance testing standardized for 80% Depth of Discharge (DoD)",
    related_standards: ["IS 16046", "IS 15549"],
    certification_information: "Mandatory for all Ministry of New and Renewable Energy (MNRE) subsidy schemes.",
    testing_information: "Ampere-hour (Ah) and Watt-hour (Wh) round-trip efficiency test, deep cycle life endurance (> 1500 cycles at 80% DoD).",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["solar battery", "tubular battery", "solar PV", "deep cycle battery", "MNRE", "renewable energy storage", "ampere hour"],
    is_verified: true
  },
  {
    standard_number: "IS 14286:2010",
    title: "Crystalline Silicon Terrestrial Photovoltaic (PV) Modules - Design Qualification and Type Approval",
    scope: "Lays down requirements for design qualification and type approval of terrestrial crystalline silicon solar photovoltaic modules suitable for long-term outdoor operation.",
    description: "The primary solar panel certification standard in India guaranteeing durability against extreme sun, hail, and monsoon humidity for 25 years.",
    category: "Electronics",
    industry: "Solar Energy & Clean Tech",
    technical_committee: "ETD 28 (Solar Photovoltaic Energy Systems Sectional Committee)",
    publication_year: 2010,
    revision_information: "Harmonized with IEC 61215",
    amendments: "Mandates PID (Potential Induced Degradation) resistance testing",
    related_standards: ["IS/IEC 61730-1", "IS/IEC 61730-2"],
    certification_information: "Mandatory BIS CRS registration under Solar Photovoltaics, Systems, Devices and Components Goods (Requirements for Compulsory Registration) Order.",
    testing_information: "Thermal cycling test (200 cycles from -40°C to +85°C), damp heat test (1000 hours at 85°C and 85% RH), hail impact test (25mm ice ball at 23 m/s), mechanical load test (2400 Pa).",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["solar panel", "solar module", "photovoltaic", "solar cell", "damp heat test", "MNRE solar", "IEC 61215", "clean tech"],
    is_verified: true
  },
  {
    standard_number: "IS 16821:2018",
    title: "Polymer-Modified Bitumen for Road Works - Specification",
    scope: "Covers the requirements of polymer-modified bitumen (PMB) produced from paving bitumen modified with elastomeric or plastomeric polymers for asphalt highway paving.",
    description: "Standard for advanced high-durability polymer bitumen used on Indian expressways to eliminate rutting and pot-holes.",
    category: "Civil Engineering",
    industry: "Highways & Road Construction",
    technical_committee: "PCD 6 (Bitumen, Tar and Related Products Sectional Committee)",
    publication_year: 2018,
    revision_information: "First Revision 2018",
    amendments: "Updated elastic recovery benchmarks at 15°C (> 70%)",
    related_standards: ["IS 73 (Paving Bitumen)", "IS 1205 (Softening point)"],
    certification_information: "Mandatory material specification under Ministry of Road Transport and Highways (MoRTH) and NHAI tenders.",
    testing_information: "Elastic recovery by ductilometer, softening point (Ring and Ball method min 55°C to 65°C), rolling thin film oven test (RTFOT) for ageing resistance.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["polymer modified bitumen", "PMB", "highway paving", "asphalt", "expressway road", "rutting resistance", "softening point", "NHAI"],
    is_verified: true
  },
  {
    standard_number: "IS 1391 (Part 1 & 2):2017",
    title: "Room Air Conditioners - Specification - Part 1: Unitary Air Conditioners; Part 2: Split Air Conditioners",
    scope: "Specifies requirements, performance ratings and test methods for room air conditioners of window and split types up to 18,000 kcal/h (approx. 2.5 TR capacity).",
    description: "Governs all residential and office window and inverter split air conditioners sold across India.",
    category: "Consumer Products",
    industry: "HVAC & Appliances",
    technical_committee: "MED 3 (Refrigeration and Air Conditioning Sectional Committee)",
    publication_year: 2017,
    revision_information: "Harmonized with Indian Seasonal Energy Efficiency Ratio (ISEER)",
    amendments: "Mandates testing using environmentally friendly refrigerants (R32, R290)",
    related_standards: ["IS 302", "IS 10617"],
    certification_information: "Mandatory ISI mark and mandatory BEE Star Labelling Program.",
    testing_information: "Calorimeter room cooling capacity test, power consumption measurement, maximum operating conditions test at 46°C ambient, sound level measurement.",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["air conditioner", "split AC", "window AC", "ISEER", "cooling capacity", "BEE star rating", "refrigerant R32", "calorimeter test"],
    is_verified: true
  },
  {
    standard_number: "IS 15700:2018",
    title: "Quality Management Systems - Requirements for Service Delivery by Public Service Organizations (Sevottam)",
    scope: "Specifies requirements for a public service organization to demonstrate its ability to consistently provide effective and citizen-centric public services meeting citizen charters.",
    description: "The official BIS standard for public administration quality (known as the Sevottam framework) implemented by government ministries and citizen service portals.",
    category: "Management & Services",
    industry: "Public Administration & Governance",
    technical_committee: "MSD 2 (Quality Management and Quality Assurance Sectional Committee)",
    publication_year: 2018,
    revision_information: "Second Revision 2018",
    amendments: "Integrated digital citizen grievance redressal metrics and portal uptime SLAs",
    related_standards: ["IS/ISO 9001", "IS 10002 (Customer satisfaction)"],
    certification_information: "Awarded by BIS Management Systems Certification Scheme (MSCS) to government departments, tax offices, and postal services.",
    testing_information: "Audited against citizen charter compliance, service delivery time limits, and grievance redressal resolution rates (>95%).",
    source: "Bureau of Indian Standards",
    source_url: "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails",
    keywords: ["Sevottam", "public service quality", "citizen charter", "governance", "grievance redressal", "public administration", "BIS certification"],
    is_verified: true
  }
];
